name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy PHP App via SSH and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Copy project to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.SSH_USER }}/php-app"

      - name: SSH into remote server and run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/php-app
            docker-compose down || true
            docker-compose up --build -d
